In [1]:
import numpy as np

In [2]:
a = np.arange(12)**2

In [3]:
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121])

In [4]:
i = np.array([7,4,8,3,6])

In [5]:
a[i]

array([49, 16, 64,  9, 36])

In [7]:
j = np.array([[4,7],[2,9]]) ## bidimensional array of indices

In [8]:
a[j]

array([[16, 49],
       [ 4, 81]])

# Indexing with boolean arrays

In [9]:
a = np.arange(12).reshape(3,4)

In [10]:
b = a > 4

In [11]:
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]], dtype=bool)

In [12]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [13]:
a[b] = 0   # All elements of a > 4 become 0 

In [14]:
a

array([[0, 1, 2, 3],
       [4, 0, 0, 0],
       [0, 0, 0, 0]])

# ix_() function

In [15]:
a = np.array([2,3,4,5])
b = np.array([8,5,4])
c = np.array([5,4,6,8,3])

In [16]:
ax,bx,cx = np.ix_(a,b,c)

In [17]:
ax

array([[[2]],

       [[3]],

       [[4]],

       [[5]]])

In [18]:
bx

array([[[8],
        [5],
        [4]]])

In [19]:
cx

array([[[5, 4, 6, 8, 3]]])

In [20]:
ax.shape,bx.shape,cx.shape

((4L, 1L, 1L), (1L, 3L, 1L), (1L, 1L, 5L))

In [21]:
result = ax + (bx*cx)   ## operation decided by user

In [22]:
result

array([[[42, 34, 50, 66, 26],
        [27, 22, 32, 42, 17],
        [22, 18, 26, 34, 14]],

       [[43, 35, 51, 67, 27],
        [28, 23, 33, 43, 18],
        [23, 19, 27, 35, 15]],

       [[44, 36, 52, 68, 28],
        [29, 24, 34, 44, 19],
        [24, 20, 28, 36, 16]],

       [[45, 37, 53, 69, 29],
        [30, 25, 35, 45, 20],
        [25, 21, 29, 37, 17]]])

# Linear Algebra

In [24]:
help(np.linalg.inv)

Help on function inv in module numpy.linalg.linalg:

inv(a)
    Compute the (multiplicative) inverse of a matrix.
    
    Given a square matrix `a`, return the matrix `ainv` satisfying
    ``dot(a, ainv) = dot(ainv, a) = eye(a.shape[0])``.
    
    Parameters
    ----------
    a : (..., M, M) array_like
        Matrix to be inverted.
    
    Returns
    -------
    ainv : (..., M, M) ndarray or matrix
        (Multiplicative) inverse of the matrix `a`.
    
    Raises
    ------
    LinAlgError
        If `a` is not square or inversion fails.
    
    Notes
    -----
    
    .. versionadded:: 1.8.0
    
    Broadcasting rules apply, see the `numpy.linalg` documentation for
    details.
    
    Examples
    --------
    >>> from numpy.linalg import inv
    >>> a = np.array([[1., 2.], [3., 4.]])
    >>> ainv = inv(a)
    >>> np.allclose(np.dot(a, ainv), np.eye(2))
    True
    >>> np.allclose(np.dot(ainv, a), np.eye(2))
    True
    
    If a is a matrix object, then the return valu

In [25]:
a = np.array([[1.0, 2.0], [3.0, 4.0]])

In [26]:
print a

[[ 1.  2.]
 [ 3.  4.]]


In [28]:
a.transpose()

array([[ 1.,  3.],
       [ 2.,  4.]])

In [29]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [30]:
u = np.eye(2)
u

array([[ 1.,  0.],
       [ 0.,  1.]])

In [31]:
np.trace(u)

2.0

In [32]:
help(np.trace)

Help on function trace in module numpy.core.fromnumeric:

trace(a, offset=0, axis1=0, axis2=1, dtype=None, out=None)
    Return the sum along diagonals of the array.
    
    If `a` is 2-D, the sum along its diagonal with the given offset
    is returned, i.e., the sum of elements ``a[i,i+offset]`` for all i.
    
    If `a` has more than two dimensions, then the axes specified by axis1 and
    axis2 are used to determine the 2-D sub-arrays whose traces are returned.
    The shape of the resulting array is the same as that of `a` with `axis1`
    and `axis2` removed.
    
    Parameters
    ----------
    a : array_like
        Input array, from which the diagonals are taken.
    offset : int, optional
        Offset of the diagonal from the main diagonal. Can be both positive
        and negative. Defaults to 0.
    axis1, axis2 : int, optional
        Axes to be used as the first and second axis of the 2-D sub-arrays
        from which the diagonals should be taken. Defaults are the 

In [33]:
a = np.arange(24).reshape((2,2,2,3))
a

array([[[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]],


       [[[12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23]]]])

In [36]:
np.trace(a)

array([[18, 20, 22],
       [24, 26, 28]])

In [37]:
x = [1,2,3]

In [38]:
np.power(5,x)

array([  5,  25, 125])

In [39]:
x = np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
np.add.reduce(x)

45

In [42]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45])

In [48]:
np.multiply.reduce(x)

362880

In [49]:
np.add.types

['??->?',
 'bb->b',
 'BB->B',
 'hh->h',
 'HH->H',
 'ii->i',
 'II->I',
 'll->l',
 'LL->L',
 'qq->q',
 'QQ->Q',
 'ee->e',
 'ff->f',
 'dd->d',
 'gg->g',
 'FF->F',
 'DD->D',
 'GG->G',
 'Mm->M',
 'mm->m',
 'mM->M',
 'OO->O']

In [50]:
np.multiply.types

['??->?',
 'bb->b',
 'BB->B',
 'hh->h',
 'HH->H',
 'ii->i',
 'II->I',
 'll->l',
 'LL->L',
 'qq->q',
 'QQ->Q',
 'ee->e',
 'ff->f',
 'dd->d',
 'gg->g',
 'FF->F',
 'DD->D',
 'GG->G',
 'mq->m',
 'qm->m',
 'md->m',
 'dm->m',
 'OO->O']

In [51]:
np.multiply.outer(x,x)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 7, 14, 21, 28, 35, 42, 49, 56, 63],
       [ 8, 16, 24, 32, 40, 48, 56, 64, 72],
       [ 9, 18, 27, 36, 45, 54, 63, 72, 81]])

In [52]:
sum(x)

45

In [53]:
%timeit sum(np.random.randint(low=1, high=100, size=(10000)))

The slowest run took 60.57 times longer than the fastest. This could mean that an intermediate result is being cached.
1000 loops, best of 3: 1.36 ms per loop


In [54]:
%timeit min(np.random.randint(low=1, high=100, size=(10000)))

1000 loops, best of 3: 950 µs per loop


In [55]:
%timeit np.sum(np.random.randint(low=1, high=100, size=(10000)))

10000 loops, best of 3: 139 µs per loop


In [56]:
%timeit np.min(np.random.randint(low=1, high=100, size=(10000)))

10000 loops, best of 3: 146 µs per loop
