# Functions and Methods

In [2]:
import numpy as np

In [4]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [5]:
np.eye(2)   

array([[ 1.,  0.],
       [ 0.,  1.]])

In [6]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [7]:
np.eye(5,k=0)   ## k = 0 for center diagonal elements to be one

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [8]:
np.eye(5,k=-1)  ## k = -1 for one below the center diagonal elements to be one

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.]])

In [9]:
np.eye(5,k=1)  ## k = 1 for one above the center diagonal elements to be one

array([[ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [12]:
np.logspace(2,3,num=6)  ## divides equally in the logarithmic interval of 10 to the power 2 to 10 to the power 3 into 6 elements

array([  100.        ,   158.48931925,   251.18864315,   398.10717055,
         630.95734448,  1000.        ])

In [13]:
np.logspace(2,3,num=6, endpoint = False) ## endpoint of 10 to the power 3 may not exactly be the criterial for number generation

array([ 100.        ,  146.77992676,  215.443469  ,  316.22776602,
        464.15888336,  681.29206906])

In [14]:
np.logspace(2,3,num=6, base = 7) ### to mentiion the required base

array([  49.        ,   72.31288492,  106.7174148 ,  157.49069664,
        232.4205433 ,  343.        ])

In [15]:
x = np.array([1,2,2.7])
x

array([ 1. ,  2. ,  2.7])

In [16]:
x.astype(int)  ### To convert from float to int

array([1, 2, 2])