In [1]:
import pandas as pd

In [2]:
s = pd.Series([5,6,7,8,9])

In [3]:
s

0    5
1    6
2    7
3    8
4    9
dtype: int64

In [4]:
type(s.values)

numpy.ndarray

In [5]:
s.values

array([5, 6, 7, 8, 9], dtype=int64)

In [6]:
s.index 

RangeIndex(start=0, stop=5, step=1)

In [7]:
t = pd.Series([7,8,9,10,11,12],index=['abi','def','ghi','jik','kjh','qwr'])

In [8]:
t

abi     7
def     8
ghi     9
jik    10
kjh    11
qwr    12
dtype: int64

In [9]:
s[1]

6

In [10]:
t['abi']

7

In [11]:
t = pd.Series([7,8,9,10,11,12],index=['abi','def','ghi','jik','kjh','jik']) 

# Here, index can be repeated multiple times and series supports this as compared to dictionary

In [12]:
t

abi     7
def     8
ghi     9
jik    10
kjh    11
jik    12
dtype: int64

In [13]:
t['jik']

jik    10
jik    12
dtype: int64

In [14]:
db = {'mumbai': 10000, 'kashmir': 5000, 'delhi': 3000}

In [15]:
db

{'delhi': 3000, 'kashmir': 5000, 'mumbai': 10000}

In [16]:
sb_s = pd.Series(db)

In [17]:
sb_s

delhi       3000
kashmir     5000
mumbai     10000
dtype: int64

In [18]:
sb_s.index

Index([u'delhi', u'kashmir', u'mumbai'], dtype='object')

In [19]:
sb_s['delhi':'kashmir']

delhi      3000
kashmir    5000
dtype: int64

In [20]:
sb_s['delhi']

3000

In [21]:
sb_s['delhi'] = 7000

In [22]:
sb_s

delhi       7000
kashmir     5000
mumbai     10000
dtype: int64

In [24]:
sb_s['ghi'] = 89

In [25]:
sb_s

delhi       7000
kashmir     5000
mumbai     10000
ghi           89
dtype: int64

In [26]:
s = pd.Series([1,2,3],index=['a','b','c'])

In [27]:
s

a    1
b    2
c    3
dtype: int64

In [28]:
s['a']

1

In [29]:
t = pd.Series(5,index=[100,200,300])

In [30]:
t

100    5
200    5
300    5
dtype: int64

In [31]:
t[100]

5

# Data Frames

In [32]:
s1 = pd.Series([1,2,3,4])

In [34]:
s2 = pd.Series(['a','b','c','d'])

In [41]:
df = pd.DataFrame({'name':s2,'age':s1})

In [42]:
df

age name
0    1    a
1    2    b
2    3    c
3    4    d

In [43]:
s1 = pd.Series([1,2,3,4])
s2 = pd.Series(['a','b','c','d'],index=[4,5,6,7])

In [44]:
df = pd.DataFrame({'name':s2,'age':s1})

In [45]:
df

age name
0  1.0  NaN
1  2.0  NaN
2  3.0  NaN
3  4.0  NaN
4  NaN    a
5  NaN    b
6  NaN    c
7  NaN    d

In [46]:
df.index

Int64Index([0, 1, 2, 3, 4, 5, 6, 7], dtype='int64')

In [47]:
df['age']

0    1.0
1    2.0
2    3.0
3    4.0
4    NaN
5    NaN
6    NaN
7    NaN
Name: age, dtype: float64

In [48]:
df['name']

0    NaN
1    NaN
2    NaN
3    NaN
4      a
5      b
6      c
7      d
Name: name, dtype: object

In [50]:
import numpy as np

In [52]:
data = np.random.randint(10,size = (5,5))

In [53]:
data

array([[4, 2, 4, 8, 3],
       [9, 1, 6, 5, 2],
       [4, 8, 6, 0, 6],
       [6, 9, 8, 5, 8],
       [3, 6, 3, 1, 4]])

In [54]:
df1 = pd.DataFrame(data, columns=['a','b','c','d','e'],index = ['r1','r2','r3','r4','r5'])

In [55]:
df1

a  b  c  d  e
r1  4  2  4  8  3
r2  9  1  6  5  2
r3  4  8  6  0  6
r4  6  9  8  5  8
r5  3  6  3  1  4

In [56]:
type(df1)

pandas.core.frame.DataFrame

In [58]:
df1['a']['r1'] 

### Always index first column and then row.

4

In [59]:
df1['d']['r4']

5

In [60]:
df1[::2]

a  b  c  d  e
r1  4  2  4  8  3
r3  4  8  6  0  6
r5  3  6  3  1  4

In [61]:
df1[::3]

a  b  c  d  e
r1  4  2  4  8  3
r4  6  9  8  5  8

In [62]:
idx = pd.Index(range(5))

In [63]:
data = pd.DataFrame({'num': range(10,15)},index = idx)

In [64]:
data

num
0   10
1   11
2   12
3   13
4   14

In [65]:
d = pd.Series(range(10,20), index=range(100,120,2))

In [66]:
d

100    10
102    11
104    12
106    13
108    14
110    15
112    16
114    17
116    18
118    19
dtype: int64

# loc, iloc & ix
# loc - access elements using configured index
# iloc - access elemts using index location
# ix - if labels r there it behaves like loc & if not behaves like iloc

In [67]:
d.loc[110]

15

In [68]:
d.loc[118]

19

In [69]:
d.iloc[0]

10

In [70]:
d.iloc[9]

19

In [71]:
d = pd.Series([1,2,3,4])

In [72]:
d.ix[3]

4

In [73]:
d.ix[0]

1

In [74]:
d = pd.Series([1,2,3,4],index = [4,5,6,7])

In [75]:
d.ix[7]

4

In [76]:
d.ix[4]

1

In [77]:
d.ix[0]

KeyError: 0L

In [78]:
area = pd.Series({'California': 423967, 'Texas': 695662,
                  'New York': 141297, 'Florida': 170312,
                  'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                 'New York': 19651127, 'Florida': 19552860,
                 'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'pop':pop})
data

area       pop
California  423967  38332521
Florida     170312  19552860
Illinois    149995  12882135
New York    141297  19651127
Texas       695662  26448193

In [79]:
data['area']

California    423967
Florida       170312
Illinois      149995
New York      141297
Texas         695662
Name: area, dtype: int64

In [80]:
data.area

California    423967
Florida       170312
Illinois      149995
New York      141297
Texas         695662
Name: area, dtype: int64

In [81]:
data['pop']

California    38332521
Florida       19552860
Illinois      12882135
New York      19651127
Texas         26448193
Name: pop, dtype: int64

In [82]:
data.pop

<bound method DataFrame.pop of               area       pop
California  423967  38332521
Florida     170312  19552860
Illinois    149995  12882135
New York    141297  19651127
Texas       695662  26448193>

In [84]:
data['density'] = data['pop']/data['area']

In [85]:
data['density']

California     90.413926
Florida       114.806121
Illinois       85.883763
New York      139.076746
Texas          38.018740
Name: density, dtype: float64

In [86]:
data

area       pop     density
California  423967  38332521   90.413926
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763
New York    141297  19651127  139.076746
Texas       695662  26448193   38.018740

In [87]:
data.values

array([[  4.23967000e+05,   3.83325210e+07,   9.04139261e+01],
       [  1.70312000e+05,   1.95528600e+07,   1.14806121e+02],
       [  1.49995000e+05,   1.28821350e+07,   8.58837628e+01],
       [  1.41297000e+05,   1.96511270e+07,   1.39076746e+02],
       [  6.95662000e+05,   2.64481930e+07,   3.80187404e+01]])

In [88]:
data.T

California       Florida      Illinois      New York         Texas
area     4.239670e+05  1.703120e+05  1.499950e+05  1.412970e+05  6.956620e+05
pop      3.833252e+07  1.955286e+07  1.288214e+07  1.965113e+07  2.644819e+07
density  9.041393e+01  1.148061e+02  8.588376e+01  1.390767e+02  3.801874e+01

In [89]:
data

area       pop     density
California  423967  38332521   90.413926
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763
New York    141297  19651127  139.076746
Texas       695662  26448193   38.018740

In [90]:
data.iloc[2:4,:2]

area       pop
Illinois  149995  12882135
New York  141297  19651127

In [92]:
data['area'][2]

149995

In [94]:
data.loc['Florida':'New York']

area       pop     density
Florida   170312  19552860  114.806121
Illinois  149995  12882135   85.883763
New York  141297  19651127  139.076746

In [95]:
data.ix[:3,:'pop']

area       pop
California  423967  38332521
Florida     170312  19552860
Illinois    149995  12882135

In [96]:
d = pd.Series([1,2,3,4] ,index=['a','b','c','d'])

In [98]:
d.ix[:'c']

a    1
b    2
c    3
dtype: int64

In [99]:
d.ix[:3]

a    1
b    2
c    3
dtype: int64

In [100]:
d.ix[3]

4

In [103]:
# In loc - we are giving criteria also
data.loc[data.density > 100, ['density','pop']]

density       pop
Florida   114.806121  19552860
New York  139.076746  19651127

In [102]:
data

area       pop     density
California  423967  38332521   90.413926
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763
New York    141297  19651127  139.076746
Texas       695662  26448193   38.018740

In [104]:
data[data.density > 100]

area       pop     density
Florida   170312  19552860  114.806121
New York  141297  19651127  139.076746

In [105]:
data[1:3]

area       pop     density
Florida   170312  19552860  114.806121
Illinois  149995  12882135   85.883763